name: your-playing-chess
services:
  backend:
    image: cryptic/ypc/backend
    container_name: ypc-backend
    build:
      context: YPC backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ypc-database:3306/ypc
      spring.datasource.username: javauser
      spring.datasource.password: password

    ports:
      - "8080:8081"

  mysql:
    image: 'mysql:latest'
    container_name: ypc-database
    restart: always
    volumes:
      - YPC:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ypc
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: javauser
    ports:
      - '3309:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      retries: 3
      timeout: 5s
      interval: 5s


volumes:
  YPC: