name: your-playing-chess
services:
  mysql:
    image: 'mysql:latest'
    container_name: database
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3307:3306'

volumes:
  YPC: